export const TEXT = {
  nav: {
    brand: 'DDay',
    createButton: 'New Event',
  },
  landing: {
    heroTitle: 'Count Every Day',
    heroSubtitle: 'Track your most important dates and milestones.',
    createCta: 'Create Your First Event',
    emptyTitle: 'No events yet',
    emptySubtitle: 'Create your first DDay event to start counting down.',
    loadingText: 'Loading events...',
    errorText: 'Failed to load events. Please try again.',
    ddayLabel: (n: number) => n === 0 ? 'D-Day' : n > 0 ? `D-${n}` : `D+${Math.abs(n)}`,
  },
  create: {
    pageTitle: 'New Event',
    pageSubtitle: 'Set up your countdown event.',
    titleLabel: 'Event Title',
    titlePlaceholder: 'e.g. Graduation Day',
    dateLabel: 'Target Date',
    noteLabel: 'Note (optional)',
    notePlaceholder: 'Add a short description...',
    colorLabel: 'Accent Color',
    submitButton: 'Create Event',
    cancelButton: 'Cancel',
    submittingButton: 'Creating...',
    successMessage: 'Event created successfully.',
    errorMessage: 'Failed to create event. Please try again.',
  },
  detail: {
    loadingText: 'Loading event...',
    errorText: 'Event not found.',
    daysUnit: 'Days',
    hoursUnit: 'Hours',
    minutesUnit: 'Minutes',
    secondsUnit: 'Seconds',
    shareButton: 'Share',
    deleteButton: 'Delete',
    deleteConfirm: 'Delete this event? This action cannot be undone.',
    shareSuccess: 'Link copied to clipboard.',
    deleteError: 'Failed to delete event.',
    noteLabel: 'Note',
    createdLabel: 'Created',
    backButton: 'Back',
    ddayLabel: (n: number) => n === 0 ? 'D-Day' : n > 0 ? `D-${n}` : `D+${Math.abs(n)}`,
  },
  colors: {
    options: [
      { value: '#6366F1', label: 'Indigo' },
      { value: '#8B5CF6', label: 'Violet' },
      { value: '#F59E0B', label: 'Amber' },
      { value: '#EF4444', label: 'Red' },
      { value: '#10B981', label: 'Emerald' },
      { value: '#EC4899', label: 'Pink' },
      { value: '#06B6D4', label: 'Cyan' },
    ],
  },
} as const;
