export const TEXT = {
  nav: {
    brand: 'DDay',
    createButton: 'New Event',
  },
  landing: {
    heroTitle: 'D-Day Counter',
    heroSubtitle: 'Track your most important dates and count down in real time.',
    createCta: 'Create First Event',
    emptyTitle: 'No events yet',
    emptySubtitle: 'Create a D-Day event and start your countdown.',
    loadingText: 'Loading...',
    errorText: 'Failed to load events. Please try again.',
    ddayLabel: (n: number) => n === 0 ? 'D-Day' : n > 0 ? `D-${n}` : `D+${Math.abs(n)}`,
    relativeLabel: (n: number) => n === 0 ? 'Today' : n > 0 ? `In ${n} days` : `${Math.abs(n)} days ago`,
  },
  create: {
    pageTitle: 'New Event',
    pageSubtitle: 'Set up your countdown event.',
    titleLabel: 'Event Title',
    titlePlaceholder: 'e.g. Graduation',
    dateLabel: 'Target Date',
    noteLabel: 'Note (optional)',
    notePlaceholder: 'Add a short description...',
    colorLabel: 'Color',
    submitButton: 'Create Event',
    cancelButton: 'Cancel',
    submittingButton: 'Creating...',
    successMessage: 'Event created.',
    errorMessage: 'Failed to create event. Please try again.',
  },
  detail: {
    loadingText: 'Loading...',
    errorText: 'Event not found.',
    daysUnit: 'days',
    hoursUnit: 'hours',
    minutesUnit: 'min',
    secondsUnit: 'sec',
    shareButton: 'Share',
    deleteButton: 'Delete',
    deleteConfirm: 'Delete this event? This cannot be undone.',
    shareSuccess: 'Link copied.',
    deleteError: 'Failed to delete.',
    noteLabel: 'Note',
    createdLabel: 'Created',
    backButton: 'Back',
    ddayLabel: (n: number) => n === 0 ? 'D-Day' : n > 0 ? `D-${n}` : `D+${Math.abs(n)}`,
  },
  colors: {
    options: [
      { value: '#6366F1', label: 'Indigo' },
      { value: '#8B5CF6', label: 'Violet' },
      { value: '#F59E0B', label: 'Amber' },
      { value: '#EF4444', label: 'Red' },
      { value: '#10B981', label: 'Emerald' },
      { value: '#EC4899', label: 'Pink' },
      { value: '#06B6D4', label: 'Cyan' },
    ],
  },
} as const;
