export const TEXT = {
  nav: {
    brand: 'DDay',
    createButton: '새 이벤트',
  },
  landing: {
    heroTitle: 'D-Day 카운터',
    heroSubtitle: '중요한 날을 기억하고 카운트다운하세요.',
    createCta: '첫 이벤트 만들기',
    emptyTitle: '이벤트가 없습니다',
    emptySubtitle: 'D-Day 이벤트를 만들어 카운트다운을 시작하세요.',
    loadingText: '불러오는 중...',
    errorText: '이벤트를 불러오지 못했습니다. 다시 시도해 주세요.',
    ddayLabel: (n: number) => n === 0 ? 'D-Day' : n > 0 ? `D-${n}` : `D+${Math.abs(n)}`,
    relativeLabel: (n: number) => n === 0 ? '오늘' : n > 0 ? `${n}일 후` : `${Math.abs(n)}일 전`,
  },
  create: {
    pageTitle: '새 이벤트',
    pageSubtitle: '카운트다운 이벤트를 설정하세요.',
    titleLabel: '이벤트 제목',
    titlePlaceholder: '예) 졸업식',
    dateLabel: '목표 날짜',
    noteLabel: '메모 (선택)',
    notePlaceholder: '짧은 설명을 입력하세요...',
    colorLabel: '색상',
    submitButton: '이벤트 만들기',
    cancelButton: '취소',
    submittingButton: '만드는 중...',
    successMessage: '이벤트가 생성되었습니다.',
    errorMessage: '이벤트 생성에 실패했습니다. 다시 시도해 주세요.',
  },
  detail: {
    loadingText: '불러오는 중...',
    errorText: '이벤트를 찾을 수 없습니다.',
    daysUnit: '일',
    hoursUnit: '시간',
    minutesUnit: '분',
    secondsUnit: '초',
    shareButton: '공유',
    deleteButton: '삭제',
    deleteConfirm: '이 이벤트를 삭제할까요? 되돌릴 수 없습니다.',
    shareSuccess: '링크가 복사되었습니다.',
    deleteError: '삭제에 실패했습니다.',
    noteLabel: '메모',
    createdLabel: '생성일',
    backButton: '뒤로',
    ddayLabel: (n: number) => n === 0 ? 'D-Day' : n > 0 ? `D-${n}` : `D+${Math.abs(n)}`,
  },
  colors: {
    options: [
      { value: '#6366F1', label: '인디고' },
      { value: '#8B5CF6', label: '바이올렛' },
      { value: '#F59E0B', label: '앰버' },
      { value: '#EF4444', label: '레드' },
      { value: '#10B981', label: '에메랄드' },
      { value: '#EC4899', label: '핑크' },
      { value: '#06B6D4', label: '시안' },
    ],
  },
} as const;
